---
- name: Create service account for Papertrail
  user: name=papertrail
        system=yes
        home=/var/lib/papertrail
        shell=/bin/false
        state=present

- name: Download Papertrail PEM
  get_url: url="https://papertrailapp.com/tools/papertrail-bundle.pem"
           dest="/etc/papertrail-bundle.pem"
           sha256sum="7019189e20ed695e9092e67d91a3b37249474f4c4c6355193ce6d2cb648f147c"
           mode=0644

- name: Install TLS support for Rsyslog
  apt: name=rsyslog-gnutls state=present

- name: Download remote_syslog
  get_url: url="https://github.com/papertrail/remote_syslog2/releases/download/v{{ papertrail_version }}/remote_syslog_linux_amd64.tar.gz"
           dest="/usr/local/src/remote_syslog_{{ papertrail_version }}_linux_amd64.tar.gz"

- name: Extract remote_syslog
  unarchive: src="/usr/local/src/remote_syslog_{{ papertrail_version }}_linux_amd64.tar.gz"
             dest=/opt
             copy=no
             owner=root
             group=root
             creates=/opt/remote_syslog/remote_syslog

- name: Configure Rsyslog to use Papertrail
  template: src="90-papertrail.conf.j2"
            dest="/etc/rsyslog.d/90-papertrail.conf"
  notify:
    - Restart rsyslog

- name: Create Papertrail service
  template: src=remote_syslog.service.j2 dest=/lib/systemd/system/remote_syslog.service mode=644
  notify:
    - Reload systemctl
    - Restart remote_syslog

- name: Configure Papertrail service
  template: src=log_files.yml.j2 dest=/etc/log_files.yml mode=644
  notify:
    - Restart remote_syslog
