---
- name: Restart rsyslog
  service: name=rsyslog state=restarted

- name: Reload systemctl
  command: systemctl daemon-reload

- name: Restart remote_syslog
  service: name=remote_syslog state=restarted enabled=yes

